version: '1.0'

configurations:
  default:
    restart: always
    network_mode: host
    volumes:
      - /data:/data
      - /secrets:/secrets
      # avahi socket
      - /var/run/avahi-daemon/socket:/var/run/avahi-daemon/socket